Repository avantifellows/plio-frontend, pull requests merged in 2022-01, with the labels that each got.

#572 Updated workflow to include timestamp in the image tag
  .github/workflows/deploy_to_ecs_prod.yml
  .github/workflows/deploy_to_ecs_staging.yml
Labels: enhancement

#593 Updated Pre-Commit.md
  docs/PRE-COMMIT.md
Labels: documentation

#605 Dragging questions to the end of the video makes the marker disappear
  src/components/UI/Slider/SliderWithMarkers.vue
Labels: bug

#603 Phone number digits can not be entered more than 10 and 0 input invalid
  src/components/UI/Text/InputNumber.vue
Labels: bug
