Repository avantifellows/plio-frontend, pull requests merged in 2022-02, with the labels that each got.

#570 Feature/settings menu skip configurable
  src/App.vue
  src/assets/images/settings.svg
  src/assets/images/times-circle-white.svg
  src/assets/locales/en.js
  src/assets/locales/hi.js
  src/components/App/EmbedPlioDialog.vue
  src/components/App/Settings.vue
  src/components/App/SharePlioDialog.vue
  src/components/App/WorkspaceSwitcher.vue
  src/components/Collections/ListItems/PlioListItem.vue
  src/components/Collections/Table/Table.vue
  src/components/Editor/ItemEditor.vue
  src/components/Editor/QuestionTypeDropdown.vue
  src/components/Items/Question/Header.vue
  src/components/Items/Scorecard.vue
  src/components/Player/ItemModal.vue
  src/components/UI/Alert/ImageUploaderDialog.vue
  src/components/UI/Buttons/IconButton.vue
  src/components/UI/Selectors/ListSingleSelector.vue
  src/components/UI/Selectors/OptionDropdown.vue
  src/components/UI/Slider/SliderWithMarkers.vue
  src/components/UI/Text/TimeInput.vue
  src/components/UI/Text/URL.vue
  src/index.css
  src/main.js
  src/pages/Dashboard.vue
  src/pages/Editor.vue
  src/pages/Embeds/Plio.vue
  src/pages/Error.vue
  src/pages/Home.vue
  src/pages/Login.vue
  src/pages/Player.vue
  src/router/index.js
  src/services/API/Endpoints.js
  src/services/API/Organization.js
  src/services/API/Plio.js
  src/services/API/RootClient.js
  src/services/API/User.js
  src/services/Config/GlobalDefaultSettings.js
  src/services/Functional/User.js
  src/services/Functional/Utilities/Generic.js
  src/services/Functional/Utilities/Settings.js
  src/store/modules/auth.js
  tailwind.config.js
  tests/integration/plugins/index.js
  tests/unit/App.spec.js
  tests/unit/components/App/EmbedPlioDialog.spec.js
  tests/unit/components/App/Settings.spec.js
  tests/unit/components/App/WorkspaceSwitcher.spec.js
  tests/unit/components/Collections/ListItems/PlioListItem.spec.js
  tests/unit/components/Collections/Table/Table.spec.js
  tests/unit/components/Items/Scorecard.spec.js
  tests/unit/pages/Dashboard.spec.js
  tests/unit/pages/Editor.spec.js
  tests/unit/pages/Home.spec.js
  tests/unit/pages/Login.spec.js
  tests/utils/dummyData.js
Labels: enhancement

#604 Adds support for OTP resend + fixes icon alignment
  src/assets/locales/en.js
  src/assets/locales/hi.js
  src/components/UI/Text/InputNumber.vue
  src/pages/Login.vue
  tests/unit/pages/Login.spec.js
Labels: enhancement

#613 Adds thumbnail to plios on the home page
  src/App.vue
  src/assets/images/video-thumbnail.svg
  src/components/Collections/ListItems/PlioListItem.vue
  src/components/UI/Text/InputNumber.vue
  src/components/UI/Text/InputText.vue
  src/components/UI/Text/Textarea.vue
  src/pages/Dashboard.vue
  src/services/Functional/Video.js
  tests/unit/components/Collections/ListItems/PlioListItem.spec.js
  tests/unit/pages/Dashboard.spec.js
Labels: feature

#620 Prevents empty rows from being shown when transitioning to workspace with no plios
  src/pages/Home.vue
Labels: bug

#626 Adding survey mode in the question editor
  src/assets/locales/en.js
  src/assets/locales/hi.js
  src/components/Editor/ItemEditor.vue
  src/pages/Editor.vue
  src/services/API/Question.js
  tests/unit/components/Editor/ItemEditor.spec.js
Labels: feature
